AllCops:
  TargetRubyVersion: 2.6

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Variable

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 62

Metrics/ClassLength:
  Max: 208

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 7

Metrics/LineLength:
  Max: 160
